# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.mguy:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '1000'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80'
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '-off'
            XDEBUG_CONFIG: '-client_host=host.docker.internal'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: '2a2eb178f35ba3539399362a9fabde8a'
            MYSQL_DATABASE: 'mguy'
            MYSQL_USER: 'mguy'
            MYSQL_PASSWORD: 'a98b6c44abac00a86b65637a40afc725'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p a98b6c44abac00a86b65637a40afc725"]
          retries: 3
          timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local