version: '3'
services:
  app:
    build: .
    ports:
      - "8009:8000"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mguy
      - MYSQL_USER=mguy
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"